version: '3'
# Keep in mind the version number.

services:
    nginx:
        build: .
        ports:
        # Ports (unlike expose) make the container's ports accesible outside
        # of the container network. This command allows us to see port 80 from
        # your system. 
            - 80:81
            - 443:443
           #- <system port>:<container port>
           # In other words, map port 81 in the nginx container to port 80
           # on the system. 
           #
        networks:
            - network1_default
            - network2_default
#            - mattermostdocker_default
        external_links:
            - network1_flask1_1:flask11
            - network1_flask2_1:flask12
            - network2_flask1_1:flask21
            - mattermostdocker_web_1:mattersmost

networks:
    network1_default:
        external:
           name: network1_default 
    network2_default:
        external:
           name: network2_default 
#    mattermostdocker_default:
#        external:
#            name: mattermostdocker_default
